/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cari dan saring daftar dataset
         * @description Mengembalikan daftar dataset berhalaman, sesuai isi halaman Datasets di portal.
         *
         *     **Cara tercepat menampilkan semua:** tekan Execute tanpa mengisi apa pun.
         *     Seluruh penyaring bersifat opsional — yang dikosongkan tidak dikirim.
         *
         *     **Contoh pemakaian:**
         *     - Cari kata kunci → isi `search` dengan `penjualan`
         *     - Saring dua topik → isi `topics` dua baris: `Keuangan` lalu `Operasional`
         *     - Saring dua divisi → isi `divisions` dua baris: `SALES` lalu `FIN`
         *     - Urutkan terpopuler → isi `sort` dengan `downloads`
         *
         *     **Membaca hasilnya:** `content` berisi datasetnya, `totalElements` jumlah seluruhnya,
         *     `totalPages` jumlah halaman, dan `number` halaman saat ini — **dimulai dari 0**, bukan 1.
         *
         *     Ambil nilai `slug` dari hasil di sini untuk dipakai di endpoint lain.
         */
        get: operations["index"];
        put?: never;
        /**
         * Terbitkan dataset baru dari berkas CSV
         * @description **Versi internal untuk pengujian.** Desain sisi penerbit belum ada, jadi bentuk
         *     layarnya masih bisa berubah — tapi pembagian tugasnya sudah pasti: apa yang bisa
         *     diverifikasi mesin dihitung sendiri, apa yang butuh pertanggungjawaban manusia diminta
         *     dari penerbit.
         *
         *     Permintaan berupa **multipart**:
         *     - `files` — satu atau beberapa berkas (CSV, XLSX, PDF, DOCX). Maksimal 10 MB per
         *       berkas, 40 MB seluruhnya, dan paling banyak 10 berkas.
         *     - `body` — metadata dalam JSON
         *
         *     **Beberapa berkas dalam satu dataset.** Yang dibaca isinya menjadi tabel hanya
         *     **CSV pertama**; sisanya tersimpan sebagai berkas pendamping yang bisa diunduh — sama
         *     seperti XLSX dan PDF pada dataset contoh. Dataset tanpa CSV sama sekali tetap sah:
         *     berkasnya bisa diunduh, hanya `/datastore`-nya yang kosong.
         *
         *     **Keterangan tiap berkas** dikirim lewat `body.files`, dan **dipasangkan menurut
         *     urutan** dengan bagian `files`. Jumlah keduanya harus sama persis. Boleh dikosongkan
         *     kalau tidak perlu memberi nama sendiri.
         *
         *     **Yang dihitung sendiri, tidak perlu diisi:**
         *
         *     | Field | Dari mana |
         *     |---|---|
         *     | `slug` | dibuat dari judul bila dikosongkan |
         *     | `division` | dari akun pengunggah — tidak bisa mengaku mewakili divisi lain |
         *     | `rowCount`, `colCount`, `fileSize` | dihitung dari berkasnya |
         *     | `format` | ekstensi tiap berkas |
         *     | daftar kolom, tipe data | dibaca dari header dan **isi** berkas |
         *
         *     **Soal tipe kolom:** untuk kolom di luar 17 kolom CSV penjualan furnitur, tipe data
         *     ditebak dari mencicipi 200 nilai pertama. Tebakannya konservatif — ragu berarti `Text`.
         *     Salah menebak kolom angka sebagai teks hanya membuat grafik tidak menawarkan kolom itu;
         *     sebaliknya akan membuat perhitungan diam-diam mengabaikan baris yang tidak terbaca dan
         *     menghasilkan angka yang salah tanpa peringatan.
         *
         *     **Soal slug:** kosongkan agar dibuatkan dari judul. Bila Anda mengisinya sendiri dan
         *     slug itu sudah dipakai, permintaan ditolak 400 beserta usulan yang tersedia — **tidak**
         *     diam-diam ditambahi angka, karena tautan yang sudah terlanjur dibagikan akan menunjuk
         *     ke tempat yang salah.
         *
         *     Perlu peran **ADMIN** atau **PUBLISHER**. Identitas uji yang bisa dipakai:
         *     `dummy-admin`, `dummy-director`, `dummy-corpsec`, `dummy-manager`.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{slug}/reimport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Baca ulang isi tabel dari berkas yang sudah tersimpan
         * @description Menghapus baris dan kolom dataset ini, lalu menulisnya ulang dari berkas **CSV atau
         *     Excel** miliknya yang sudah ada di penyimpanan. Berkasnya sendiri tidak diunggah ulang
         *     dan tidak berubah.
         *
         *     **Kapan dipakai:**
         *     - Dataset diunggah sebelum portal bisa membaca Excel, sehingga tabelnya kosong.
         *     - Importir diperbaiki — penebakan tipe kolom, pemisah baru — dan dataset lama perlu
         *       ikut menikmati perbaikannya.
         *
         *     Metadata tidak disentuh: judul, catatan, topik, tag posisi, pengunggah, dan penghitung
         *     unduhan tetap seperti semula. Pembacaan ulangnya tercatat di log audit.
         */
        post: operations["reimport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{slug}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Ganti daftar posisi yang boleh melihat
         * @description Mengganti SELURUH tag posisi sebuah dataset dengan daftar yang dikirim. Kirim daftar
         *     kosong untuk melepas semuanya.
         *
         *     Ambil nilai yang sah dari `GET /api/v1/positions`; label di luar daftar itu ditolak 400
         *     supaya tag hasil salah ketik tidak pernah tersimpan.
         *
         *     **Ini mengubah hak akses, seketika.** Daftar kosong membuat dataset terbuka untuk
         *     seluruh karyawan; daftar berisi menguncinya ke posisi-posisi itu saja. Yang tidak
         *     berhak tidak lagi melihatnya di `GET /api/v1/datasets`, dan mendapat 403 kalau membuka
         *     slug-nya langsung. ADMIN dan pengunggahnya sendiri selalu bisa.
         *
         *     Perubahannya tercatat di `GET /api/v1/audit-logs` lengkap dengan nilai sebelum dan
         *     sesudahnya.
         */
        patch: operations["updatePositions"];
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar seluruh topik
         * @description Delapan topik yang dipakai mengelompokkan dataset, sesuai chip penyaring di halaman
         *     Datasets portal.
         *
         *     Nilai `name` dari sini yang diisikan ke parameter `topics` pada
         *     `GET /api/v1/datasets`. Contoh: `Keuangan`, `Operasional`.
         *
         *     Tidak perlu login.
         */
        get: operations["indexTopic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kesehatan tiap komponen portal
         * @description Memeriksa setiap komponen secara nyata saat dipanggil — database benar-benar
         *     di-ping, penyimpanan berkas benar-benar dicek.
         *
         *     Tanpa parameter apa pun; langsung Execute.
         *
         *     **Catatan jujur:** komponen "Real-time API" akan selalu melaporkan *Belum tersedia*,
         *     bukan *Operasional* — karena fitur itu memang belum dibangun. Itu disengaja; melaporkan
         *     hijau untuk sesuatu yang tidak ada hanya menyesatkan orang yang membaca halaman status.
         *
         *     Endpoint ini berbeda dari `/actuator/health` bawaan Spring: yang ini memakai bahasa dan
         *     pengelompokan sesuai desain halaman Status, sedangkan actuator untuk pemantauan mesin.
         */
        get: operations["index_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Angka ringkas seluruh portal
         * @description Jumlah dataset, divisi penerbit, total kunjungan, total unduhan, dan total panggilan
         *     API — dihitung langsung dari database saat dipanggil, bukan nilai tetap.
         *
         *     Tanpa parameter apa pun; langsung Execute.
         *
         *     Nama endpoint ini sudah jamak sejak awal karena `stats` memang bentuk jamak dari
         *     *statistic*, bukan pengecualian dari konvensi.
         */
        get: operations["index_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/downloads/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jumlah unduhan per hari
         * @description Bahan grafik **Download harian** di dasbor admin.
         *
         *     **Cara tercepat:** tekan Execute tanpa mengisi apa pun — 30 hari terakhir.
         *
         *     **Membaca hasilnya:** `days` berisi satu baris untuk SETIAP tanggal dalam rentang,
         *     termasuk tanggal yang jumlahnya nol. Itu disengaja: grafik garis yang melompati
         *     tanggal sepi memperlihatkan tren yang tidak pernah terjadi.
         *
         *     Rentangnya berakhir hari ini, jadi baris terakhir adalah hari yang belum selesai —
         *     wajar kalau angkanya lebih rendah dari hari sebelumnya.
         */
        get: operations["dailyDownloads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar posisi jabatan
         * @description Sembilan posisi jabatan yang bisa dipakai membatasi siapa boleh melihat sebuah
         *     dataset — isi penyaring "Akses posisi" dan isian pada form terbitkan dataset.
         *
         *     **Pembatasannya berlaku sungguhan.** Dataset yang diberi tag hanya bisa dibuka,
         *     dibaca isinya, dan diunduh oleh pemilik posisi tersebut — selain ADMIN dan
         *     pengunggahnya sendiri. Dataset tanpa tag terbuka untuk seluruh karyawan.
         *
         *     Posisi setiap pengguna disimpan di kolom `users.access_position`, milik portal ini.
         *     HRIS sendiri menyimpan dua sumbu berbeda: `job_level` (enum 12 nilai) dan `position`
         *     (teks bebas seperti "Project Manager Data & IT"). Tak satu pun cocok satu-satu dengan
         *     sembilan label di bawah, jadi kolomnya dibuat sendiri dan nanti diisi dari HRIS lewat
         *     pemetaan yang ditulis sekali — pola yang sama dengan `hris_permission_level`.
         *
         *     Karena itu daftar di bawah masih tetap (hard-coded), bukan dibaca dari tabel.
         *
         *     Tidak perlu login.
         */
        get: operations["indexPosition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profil pengguna yang sedang login
         * @description Identitas pemanggil: nama, email, jabatan, divisi, peran portal, dan tingkat izin
         *     hasil hitungan HRIS.
         *
         *     Dipakai portal untuk mengisi pil identitas di header setiap halaman.
         *
         *     **Cara mencoba di Swagger:** tekan Authorize, isi `dummyAuth` dengan salah satu
         *     identitas uji, lalu Execute di sini. Nama yang muncul harus sesuai identitas yang
         *     Anda pilih.
         *
         *     | Isi `dummyAuth` | Hasil |
         *     |---|---|
         *     | `dummy-admin` | 200, peran ADMIN |
         *     | `dummy-director` | 200, izin HRIS DIRECTOR |
         *     | `dummy-staff` | 200, peran STAFF |
         *     | `dummy-resigned` | **403** — sengaja, user itu sudah resign |
         *     | *(tanpa Authorize)* | **401** |
         *
         *     Perhatikan `role` (peran di portal) berbeda dari `hrisPermissionLevel` (tingkat izin
         *     dari sistem HRIS). Keduanya sengaja dipisah karena sumbernya berbeda.
         *
         *     ⚠️ Peran portal saat ini **belum menegakkan apa pun** — belum ada satu pun
         *     `@PreAuthorize` di kode. Semua pengguna terautentikasi bisa memanggil semua endpoint.
         *     Itu masih aman karena seluruh endpoint bersifat baca atau sudah dibatasi per-pengguna,
         *     tapi penegakan role wajib ada sebelum sisi admin dibangun.
         */
        get: operations["index_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/formats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar seluruh jenis berkas
         * @description Jenis berkas yang dipakai katalog ini: **CSV, XLSX, PDF, dan DOCX**.
         *
         *     Nilai `name` dari sini yang diisikan ke parameter `formats` pada
         *     `GET /api/v1/datasets`.
         *
         *     Daftarnya dirapikan pada changeset 00026. Sebelumnya memuat GEOJSON dan KML yang tidak
         *     dipakai, serta `API` yang sebenarnya bukan jenis berkas melainkan cara pengiriman —
         *     keadaan itu sudah punya penandanya sendiri, yaitu `realtime` pada dataset.
         *
         *     Tidak perlu login.
         */
        get: operations["indexFormat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/download-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar unduhan, terbaru lebih dulu
         * @description Mengembalikan daftar berhalaman, diurutkan dari yang paling baru.
         *
         *     **Cara tercepat:** tekan Execute tanpa mengisi apa pun — 20 unduhan terbaru.
         *
         *     **Contoh pemakaian:**
         *     - Satu bulan tertentu → `from` = `2026-08-01`, `to` = `2026-08-31`
         *     - Sejak tanggal tertentu sampai sekarang → isi `from` saja, biarkan `to` kosong
         *
         *     **Perhatikan:** `to` bersifat inklusif — mengisinya dengan tanggal hari ini ikut
         *     memuat unduhan yang terjadi hari ini.
         */
        get: operations["index_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/download-logs/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ekspor log unduhan sebagai CSV
         * @description Mengunduh seluruh baris dalam rentang tanggal sebagai satu berkas CSV.
         *
         *     **Berkas ini memuat data pribadi** — nama, email, divisi, dan alamat IP karyawan.
         *     Karena itu ekspornya sendiri dicatat di `GET /api/v1/audit-logs`: "siapa yang membawa
         *     log ini keluar dari sistem" adalah persis pertanyaan yang harus bisa dijawab
         *     belakangan. Log yang dibuat untuk menelusuri kebocoran tidak boleh justru menjadi jalan
         *     paling mudah membuatnya.
         *
         *     Dibatasi 50.000 baris per ekspor. Persempit rentang tanggalnya bila hasilnya terpotong.
         */
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/divisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar seluruh divisi
         * @description Delapan divisi beserta kode, nama, warna avatar, dan penghitung pemakaian
         *     (`apiCalls`, `downloads`).
         *
         *     **Nilai `code` dari sini yang diisikan ke parameter `divisions`** pada
         *     `GET /api/v1/datasets` untuk menyaring dataset per divisi penerbit:
         *     `DNA`, `IT`, `PROD`, `SALES`, `FIN`, `OPS`, `HR`, `MKT`.
         *
         *     Mengisi parameter itu dengan nama panjang seperti `Divisi Penjualan` tidak akan
         *     menyaring apa pun — yang dipakai kodenya.
         */
        get: operations["index_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ambil metadata lengkap satu dataset
         * @description Semua keterangan tentang satu dataset: judul, divisi penerbit, catatan, disclaimer,
         *     koleksi induk, daftar topik dan format, jumlah baris dan kolom, serta **skema kolomnya**
         *     (nama mesin, nama tampilan, tipe data, satuan).
         *
         *     Dipakai halaman detail dataset di portal untuk mengisi tab Ringkasan dan tab Kolom.
         *
         *     Perhatikan `resources` — kalau kosong, dataset itu tidak punya berkas untuk diunduh.
         *
         *     **Endpoint ini menaikkan penghitung kunjungan** setiap kali dipanggil. Untuk membaca
         *     tanpa ikut menghitung — misalnya dari panel pengelolaan — isi `recordView` dengan
         *     `false`.
         */
        get: operations["getById"];
        put?: never;
        post?: never;
        /**
         * Hapus dataset dari katalog
         * @description Penghapusan bersifat **soft delete**: barisnya tetap ada di database dengan penanda
         *     `deleted_at`, tapi hilang dari seluruh daftar dan tidak bisa dibuka lagi.
         *
         *     Slug-nya TIDAK dilepas dan tidak bisa dipakai ulang. Itu disengaja — kalau slug bekas
         *     bisa diambil dataset lain, tautan lama di laporan orang akan diam-diam menunjuk ke data
         *     yang berbeda.
         *
         *     Penghapusannya tercatat di `GET /api/v1/audit-logs`.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{slug}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hitung agregat untuk bahan grafik
         * @description Mengelompokkan isi dataset lalu menghitung jumlahnya — inilah yang menggambar grafik
         *     di halaman detail portal.
         *
         *     **Cara mengisi:**
         *     - `groupBy` **wajib** — nama kolom yang jadi pengelompokan, nantinya sumbu X grafik
         *     - `metric` opsional — nama kolom angka yang dijumlahkan. Kalau dikosongkan, yang keluar
         *       hanya `count` (banyaknya baris per kelompok)
         *
         *     **Contoh untuk `penjualan-furnitur-2025`:**
         *     | Ingin melihat | `groupBy` | `metric` |
         *     |---|---|---|
         *     | Penjualan per kategori produk | `category` | `total_sales` |
         *     | Penjualan per kota | `kota` | `total_sales` |
         *     | Banyaknya transaksi per status | `status` | *(kosongkan)* |
         *     | Jumlah barang terjual per kategori | `category` | `quantity` |
         *
         *     Nama kolom yang boleh dipakai bisa dilihat dari `columns` pada
         *     `GET /api/v1/datasets/{slug}`.
         *
         *     **Peringatan angka:** kolom `status` memuat `completed`, `cancelled`, dan `refund`.
         *     Menjumlahkan `total_sales` tanpa menyaring status berarti transaksi batal ikut terhitung
         *     — jadi angkanya bukan pendapatan bersih. Penyaringan per status belum tersedia di
         *     endpoint ini.
         */
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{slug}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tampilkan berkas PDF di halaman
         * @description Mengalirkan berkas **PDF** dengan `Content-Disposition: inline`, supaya peramban
         *     menggambarnya sendiri di dalam halaman alih-alih menyimpannya ke disk.
         *
         *     **Pratinjau tetap tercatat** di log dengan `accessType = PREVIEW`. Ia tidak melewati
         *     modal persetujuan, tapi byte-nya tetap keluar dan isinya tetap terbaca utuh — berkas
         *     rahasia yang bisa dibaca tanpa jejak membuat seluruh guna log itu hilang.
         *
         *     Untuk dokumen Word, pakai `/preview/text`. Untuk CSV dan XLSX tidak perlu: isinya
         *     sudah menjadi tabel dataset.
         */
        get: operations["preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{slug}/preview/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Baca isi dokumen Word sebagai teks
         * @description Mengembalikan paragraf sebuah berkas **DOCX** dalam bentuk teks polos.
         *
         *     **Yang tidak ikut:** tata letak, tabel, gambar, header, dan footer. Peramban tidak bisa
         *     menggambar .docx, dan mengurainya tanpa mesin render dokumen hanya menghasilkan
         *     teksnya. Antarmuka menyebutkan batas ini apa adanya — pembaca yang mengira sudah
         *     melihat dokumen lengkap padahal belum akan mengambil keputusan dari setengah isi.
         *
         *     Sama seperti `/preview`, pembacaannya tercatat dengan `accessType = PREVIEW`.
         */
        get: operations["previewText"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{slug}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unduh berkas asli dataset
         * @description Mengalirkan berkas sumber dataset apa adanya, tanpa perubahan sebyte pun.
         *
         *     **`agreement` wajib diisi `true`.** Itu bukan formalitas: nilainya mewakili centang
         *     persetujuan pemakaian data pada modal di portal, dan **ikut tercatat di audit log**
         *     bersama identitas pengunduh, waktu, alamat IP, dan User-Agent. Dikirim `false` →
         *     ditolak 400. Jangan pernah mengirim `true` secara otomatis tanpa pengguna benar-benar
         *     menyetujuinya.
         *
         *     **Catatan saat mencoba lewat Swagger:** responsnya berkas 1,4 MB, dan Swagger UI akan
         *     mencoba menampilkannya sebagai teks sebelum memberi tombol "Download file" — browser
         *     bisa terasa berat beberapa detik. Untuk sekadar menguji, lebih nyaman memakai `curl`.
         *     Yang justru berguna dicoba di sini adalah kasus gagalnya: biarkan `agreement` bernilai
         *     `false` lalu Execute, harus dijawab 400.
         */
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{slug}/datastore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Baca isi tabel dataset per halaman
         * @description Isi baris data yang sesungguhnya — yang tampil di tab **Data Explorer** portal.
         *
         *     `columns` memberi urutan kolomnya, `rows` berisi datanya sebagai objek bebas
         *     (satu objek per baris, kuncinya nama kolom).
         *
         *     **Contoh:** slug `penjualan-furnitur-2025`, `page` 0, `size` 50 → 50 baris pertama
         *     dari 10.000 baris penjualan furnitur.
         *
         *     Naikkan `page` untuk melihat baris berikutnya. Dengan `size` 50, halaman 0 berisi baris
         *     1–50, halaman 1 berisi 51–100, dan seterusnya.
         *
         *     **Satu dataset bisa punya lebih dari satu tabel.** Setiap berkas CSV atau Excel di
         *     dalamnya punya baris dan kolomnya sendiri. Pakai `resourceId` untuk memilih yang mana;
         *     tanpa itu, yang dijawab adalah berkas bertanda `tableSource` pada daftar `resources`.
         */
        get: operations["datastore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar seluruh koleksi
         * @description Semua koleksi beserta nama, keterangan, dan divisi pengelolanya.
         *
         *     Ambil nilai `slug` dari sini untuk membuka detailnya.
         */
        get: operations["index_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ambil satu koleksi beserta dataset di dalamnya
         * @description Keterangan lengkap satu koleksi berikut daftar dataset anggotanya.
         *
         *     Seperti pada dataset, path parameternya **slug**, bukan UUID. Ambil nilainya dari
         *     `GET /api/v1/collections`.
         */
        get: operations["getById_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar jejak audit, terbaru lebih dulu
         * @description Mengembalikan daftar berhalaman, diurutkan dari yang paling baru.
         *
         *     **Cara tercepat:** tekan Execute tanpa mengisi apa pun — 20 baris terbaru.
         *
         *     **Contoh pemakaian:**
         *     - Riwayat satu dataset → isi `slug` dengan `penjualan-bulanan`
         *     - Ambil 6 baris untuk kartu dasbor → isi `size` dengan `6`
         *
         *     **Membaca hasilnya:** `action` adalah kata tindakannya, `objectLabel` judul dataset
         *     saat tindakan itu terjadi (bukan judul terbarunya), dan `detail` keterangan singkat
         *     yang boleh kosong. `number` adalah halaman saat ini — **dimulai dari 0**, bukan 1.
         */
        get: operations["index_7"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DatasetRequestCreateDTO: {
            /**
             * @description Nama dataset seperti yang akan dibaca orang. Ini klaim tentang apa data ini — tidak bisa ditebak dari berkasnya, jadi wajib ditulis penerbit.
             * @example Penjualan Furnitur Ritel 2025
             */
            title: string;
            /**
             * @description Alamat dataset di URL. **Kosongkan** dan sistem membuatnya dari judul. Isi hanya bila ingin lebih pendek, misalnya `utilisasi-sdm` untuk judul "Utilisasi & Kapasitas Tim". Huruf kecil, angka, dan tanda hubung saja. Setelah terbit, slug tidak bisa diubah karena sudah jadi tautan di laporan orang.
             * @example penjualan-furnitur-2025
             */
            slug?: string;
            /**
             * @description Penjelasan isi dataset dan cara membacanya.
             * @example Transaksi penjualan furnitur ritel sepanjang 2025 per pesanan.
             */
            notes?: string;
            /**
             * @description Hal yang harus diketahui pembaca agar datanya tidak salah ditafsirkan: angka yang masih sementara, batas cakupan, atau dasar perhitungan. Ditampilkan sebagai blok terpisah di halaman detail.
             * @example Status refund dan cancelled dihitung apa adanya tanpa rekonsiliasi keuangan.
             */
            disclaimer?: string;
            /**
             * @description Periode yang dicakup data.
             * @example Jan – Des 2025
             */
            coverage?: string;
            /**
             * @description Nama topik, ambil dari GET /api/v1/topics. Boleh lebih dari satu.
             * @example [
             *       "Penjualan"
             *     ]
             */
            topics?: string[];
            /**
             * @description Slug koleksi induk, ambil dari GET /api/v1/collections. Boleh kosong.
             * @example komersial
             */
            collectionSlug?: string;
            /**
             * @description Posisi jabatan yang boleh melihat dataset ini, ambil dari GET /api/v1/positions. **Kosongkan agar terbuka untuk seluruh karyawan.** Diisi berarti hanya pemilik posisi tersebut yang bisa membuka, membaca isi tabelnya, dan mengunduhnya; yang lain mendapat 403. ADMIN dan pengunggahnya sendiri selalu bisa.
             * @example [
             *       "Direksi",
             *       "General Manager",
             *       "Manager"
             *     ]
             */
            positions?: string[];
            /** @description Keterangan tiap berkas yang diunggah — nama versi manusia dan jenisnya. Urutannya HARUS sama dengan urutan bagian multipart `files`, dan jumlahnya harus sama persis. Boleh dikosongkan kalau hanya satu berkas: namanya diambil dari judul dataset dan jenisnya dari ekstensi berkasnya. */
            files?: components["schemas"]["FileMeta"][];
        };
        FileMeta: {
            /**
             * @description Nama berkas versi manusia.
             * @example Kamus Kolom
             */
            label?: string;
            /**
             * @description Jenis berkas: CSV, XLSX, PDF, atau DOCX. Harus cocok dengan ekstensi berkas yang dikirim.
             * @example CSV
             */
            format?: string;
        };
        CollectionResponseLite: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            name?: string;
        };
        DatasetColumnResponse: {
            /** Format: uuid */
            id?: string;
            machineName?: string;
            displayName?: string;
            dataType?: string;
            unit?: string;
            description?: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        DatasetResourceResponse: {
            /** Format: uuid */
            id?: string;
            label?: string;
            fileName?: string;
            formatName?: string;
            contentType?: string;
            /** Format: int64 */
            sizeBytes?: number;
            checksumSha256?: string;
            tableSource?: boolean;
            /** Format: int64 */
            rowCount?: number;
            /** Format: int32 */
            colCount?: number;
        };
        DatasetResponse: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            title?: string;
            division?: components["schemas"]["DivisionResponseLite"];
            uploadedBy?: components["schemas"]["UploaderResponse"];
            collection?: components["schemas"]["CollectionResponseLite"];
            topics?: string[];
            formats?: string[];
            positions?: string[];
            coverage?: string;
            notes?: string;
            disclaimer?: string;
            /** Format: int64 */
            rowCount?: number;
            /** Format: int32 */
            colCount?: number;
            fileSize?: string;
            /** Format: int64 */
            downloads?: number;
            /** Format: int64 */
            apiCalls?: number;
            /** Format: int64 */
            views?: number;
            realtime?: boolean;
            /** Format: date-time */
            lastUpdatedAt?: string;
            columns?: components["schemas"]["DatasetColumnResponse"][];
            resources?: components["schemas"]["DatasetResourceResponse"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string;
        };
        DivisionResponseLite: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            logoBg?: string;
        };
        UploaderResponse: {
            /** Format: uuid */
            id?: string;
            /** @example M. Fahrega Ridwan */
            name?: string;
            /**
             * @description Jabatan, apa adanya dari HRIS.
             * @example Project Manager Data & IT
             */
            position?: string;
            /**
             * @description Kode divisi pengunggah saat itu.
             * @example DNA
             */
            divisionCode?: string;
        };
        DatasetPositionUpdateDTO: {
            /**
             * @description Daftar posisi yang berlaku setelah perubahan. Kirim daftar kosong untuk melepas seluruh tag.
             * @example [
             *       "Direksi",
             *       "General Manager",
             *       "Manager"
             *     ]
             */
            positions?: string[];
        };
        TopicResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        Component: {
            name?: string;
            state?: string;
        };
        IncidentItem: {
            /** Format: uuid */
            id?: string;
            title?: string;
            tag?: string;
            detail?: string;
            occurredLabel?: string;
            /** Format: date-time */
            occurredAt?: string;
        };
        StatusResponse: {
            overall?: string;
            overallLabel?: string;
            components?: components["schemas"]["Component"][];
            incidents?: components["schemas"]["IncidentItem"][];
        };
        StatsResponse: {
            /** Format: int64 */
            totalDataset?: number;
            /** Format: int64 */
            totalFormat?: number;
            /** Format: int64 */
            totalDivision?: number;
            /** Format: int64 */
            totalTopic?: number;
            /** Format: int64 */
            totalCollection?: number;
            /** Format: int64 */
            totalDownloads?: number;
            /** Format: int64 */
            totalApiCalls?: number;
            /** Format: int64 */
            totalViews?: number;
            /** Format: int64 */
            totalDatasetWithFile?: number;
            /** Format: int64 */
            totalContributor?: number;
            /** Format: int64 */
            totalActiveUser?: number;
            /** Format: int64 */
            totalDownloads30d?: number;
        };
        DailyDownloadResponse: {
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            /** Format: int64 */
            total?: number;
            days?: components["schemas"]["Day"][];
        };
        Day: {
            /** Format: date */
            date?: string;
            /** Format: int64 */
            total?: number;
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            email?: string;
            position?: string;
            initials?: string;
            /** @enum {string} */
            role?: "ADMIN" | "PUBLISHER" | "STAFF";
            /** @enum {string} */
            hrisPermissionLevel?: "ADMIN" | "DIRECTOR" | "CORPORATE_SECRETARY" | "MANAGER" | "STAFF";
            jobLevel?: string;
            accessPosition?: string;
            division?: components["schemas"]["DivisionResponseLite"];
        };
        FormatResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        DownloadLogResponse: {
            /** Format: int64 */
            id?: number;
            userName?: string;
            userEmail?: string;
            divisionCode?: string;
            datasetSlug?: string;
            fileName?: string;
            /** Format: int64 */
            sizeBytes?: number;
            accessType?: string;
            channel?: string;
            agreementAccepted?: boolean;
            ipAddress?: string;
            /** Format: date-time */
            downloadedAt?: string;
        };
        PageDownloadLogResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["DownloadLogResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            pageSize?: number;
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        DivisionResponse: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            logoBg?: string;
            /** Format: int64 */
            apiCalls?: number;
            /** Format: int64 */
            downloads?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string;
        };
        DatasetResponseLite: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            title?: string;
            division?: components["schemas"]["DivisionResponseLite"];
            uploadedBy?: components["schemas"]["UploaderResponse"];
            topics?: string[];
            formats?: string[];
            positions?: string[];
            resources?: components["schemas"]["DatasetResourceResponse"][];
            coverage?: string;
            notes?: string;
            /** Format: int64 */
            rowCount?: number;
            /** Format: int64 */
            downloads?: number;
            /** Format: int64 */
            apiCalls?: number;
            /** Format: int64 */
            views?: number;
            realtime?: boolean;
            /** Format: date-time */
            lastUpdatedAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PageDatasetResponseLite: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["DatasetResponseLite"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        DatasetSummaryResponse: {
            slug?: string;
            groupBy?: string;
            metric?: string;
            /** Format: int64 */
            totalRows?: number;
            groups?: components["schemas"]["SummaryGroup"][];
        };
        SummaryGroup: {
            label?: string;
            /** Format: int64 */
            count?: number;
            sum?: number;
        };
        DocumentTextResponse: {
            fileName?: string;
            label?: string;
            paragraphs?: string[];
            truncated?: boolean;
        };
        DatastoreResponse: {
            slug?: string;
            /** Format: uuid */
            resourceId?: string;
            /** Format: int64 */
            totalRows?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int32 */
            totalPages?: number;
            columns?: components["schemas"]["DatasetColumnResponse"][];
            rows?: {
                [key: string]: unknown;
            }[];
        };
        CollectionResponse: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            name?: string;
            description?: string;
            division?: components["schemas"]["DivisionResponseLite"];
            /** Format: int64 */
            datasetCount?: number;
            datasets?: components["schemas"]["DatasetResponseLite"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string;
        };
        AuditLogResponse: {
            /** Format: int64 */
            id?: number;
            actorName?: string;
            actorDivisionCode?: string;
            /** @enum {string} */
            action?: "CREATE" | "UPDATE" | "SUBMIT" | "PUBLISH" | "REJECT" | "ARCHIVE" | "DELETE";
            objectType?: string;
            objectSlug?: string;
            objectLabel?: string;
            detail?: string;
            /** Format: date-time */
            recordedAt?: string;
        };
        PageAuditLogResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AuditLogResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    index: {
        parameters: {
            query?: {
                /**
                 * @description Kata kunci pada judul, slug, dan catatan dataset. Kosongkan untuk menampilkan semua.
                 * @example penjualan
                 */
                search?: string;
                /** @description Saring per topik. Ulangi parameter untuk lebih dari satu, misalnya topics=Keuangan&topics=Operasional. Daftar nilainya dari GET /api/v1/topics. */
                topics?: string[];
                /** @description Saring per jenis berkas: CSV, XLSX, PDF, DOCX. Daftar nilainya dari GET /api/v1/formats. */
                formats?: string[];
                /** @description Saring per kode divisi: DNA, IT, PROD, SALES, FIN, OPS, HR, MKT. Daftar lengkapnya dari GET /api/v1/divisions. */
                divisions?: string[];
                /**
                 * @description Saring per tag posisi yang boleh melihat. Daftar nilainya dari GET /api/v1/positions.
                 *
                 *     Ini penyaring tampilan, BUKAN pembatas akses. Pembatasannya berjalan sendiri dan tidak bisa dimatikan lewat parameter apa pun: dataset yang tidak boleh Anda lihat tidak akan muncul di sini, apa pun isian penyaringnya.
                 */
                positions?: string[];
                /** @description Urutan hasil. */
                sort?: "relevance" | "downloads" | "updated" | "created";
                /** @description Halaman ke berapa, dimulai dari 0. */
                page?: number;
                /** @description Jumlah baris per halaman. Minimal 1. */
                size?: number;
                /** @description Ikut menampilkan dataset yang sudah dihapus. */
                withDeleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar dataset berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageDatasetResponseLite"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** @description Satu atau beberapa berkas. Ulangi bagian `files` untuk tiap berkas. */
                    files: string[];
                    body: components["schemas"]["DatasetRequestCreateDTO"];
                };
            };
        };
        responses: {
            /** @description Dataset terbit, berikut isi tabel dan berkasnya */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Jenis berkas tidak didukung atau tidak cocok dengan ekstensinya, jumlah keterangan berkas tidak sama dengan jumlah berkas, judul kosong, slug bentrok, atau topik/koleksi/posisi tidak dikenal */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
            /** @description Peran Anda tidak berhak menerbitkan dataset */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    reimport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug dataset. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jumlah baris setelah dibaca ulang */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Tidak ada berkas CSV/Excel yang bisa dibaca */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bukan ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Slug tidak dikenal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePositions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Slug dataset.
                 * @example penjualan-bulanan
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetPositionUpdateDTO"];
            };
        };
        responses: {
            /** @description Tag posisi tersimpan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
            /** @description Ada label posisi yang tidak dikenal */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
            /** @description Bukan ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Slug tidak dikenal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    indexTopic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar topik berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopicResponse"][];
                };
            };
        };
    };
    index_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status berhasil diperiksa. Kode 200 tidak berarti semua komponen sehat — periksa isi responsnya */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    index_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistik berhasil dihitung */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    dailyDownloads: {
        parameters: {
            query?: {
                /**
                 * @description Panjang rentang dalam hari, dihitung mundur dari hari ini. Maksimum 365.
                 * @example 30
                 */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grafik berhasil dihitung */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DailyDownloadResponse"];
                };
            };
        };
    };
    indexPosition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar posisi berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
        };
    };
    index_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil berhasil diambil — berarti autentikasi Anda benar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Belum Authorize, atau identitas tidak dikenal */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        message?: string;
                    };
                };
            };
            /** @description Karyawan sudah resign sehingga aksesnya ditolak */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    indexFormat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar format berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FormatResponse"][];
                };
            };
        };
    };
    index_4: {
        parameters: {
            query?: {
                /**
                 * @description Halaman ke berapa, dimulai dari 0
                 * @example 0
                 */
                page?: number;
                /**
                 * @description Jumlah baris per halaman, maksimum 200
                 * @example 20
                 */
                size?: number;
                /**
                 * @description Tanggal awal, format YYYY-MM-DD. Boleh dikosongkan.
                 * @example 2026-08-01
                 */
                from?: string;
                /**
                 * @description Tanggal akhir, inklusif. Boleh dikosongkan.
                 * @example 2026-08-31
                 */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log unduhan berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageDownloadLogResponse"];
                };
            };
            /** @description Tanggal akhir mendahului tanggal awal */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bukan ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export: {
        parameters: {
            query?: {
                /** @description Tanggal awal, format YYYY-MM-DD. */
                from?: string;
                /** @description Tanggal akhir, inklusif. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Berkas CSV */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description Tanggal akhir mendahului tanggal awal */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bukan ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    index_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar divisi berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DivisionResponse"][];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: {
                /**
                 * @description Apakah pemanggilan ini dihitung sebagai kunjungan. Biarkan `true` untuk
                 *     halaman detail portal; isi `false` untuk pembacaan pengelolaan, supaya angka
                 *     "Total kunjungan" tidak naik setiap kali admin menengok datanya sendiri.
                 * @example true
                 */
                recordView?: boolean;
            };
            header?: never;
            path: {
                /**
                 * @description Identitas dataset di URL — berupa **slug**, bukan UUID.
                 *
                 *     Slug adalah versi judul yang aman dipakai di URL: huruf kecil, spasi diganti
                 *     tanda hubung. Contoh: judul "Penjualan Furnitur Ritel 2025" berslug
                 *     `penjualan-furnitur-2025`.
                 *
                 *     Daftar slug yang tersedia bisa dilihat dari `GET /api/v1/datasets`.
                 * @example penjualan-furnitur-2025
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dataset ditemukan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Slug tidak dikenal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Slug dataset.
                 * @example penjualan-bulanan
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dataset dihapus */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bukan ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Slug tidak dikenal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    summary: {
        parameters: {
            query: {
                /**
                 * @description Nama kolom pengelompokan — jadi sumbu X grafik. Contoh lain: `kota`, `status`.
                 * @example category
                 */
                groupBy: string;
                /**
                 * @description Nama kolom angka yang dijumlahkan. Kosongkan untuk sekadar menghitung banyaknya baris.
                 * @example total_sales
                 */
                metric?: string;
                /**
                 * @description Tabel milik berkas yang mana, dari daftar `resources`. Kosongkan untuk berkas utama.
                 * @example dres-f0000000-0000-4000-8000-000000000001
                 */
                resourceId?: string;
            };
            header?: never;
            path: {
                /**
                 * @description Slug dataset.
                 * @example penjualan-furnitur-2025
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agregat berhasil dihitung */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DatasetSummaryResponse"];
                };
            };
            /** @description Kolom groupBy atau metric tidak ada di dataset ini */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
            /** @description Slug tidak dikenal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: {
                /** @description Berkas mana yang dilihat, dari daftar `resources`. */
                resourceId?: string;
            };
            header?: never;
            path: {
                /**
                 * @description Slug dataset.
                 * @example penjualan-bulanan
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Berkas dialirkan untuk digambar peramban */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Jenis berkas tidak bisa digambar peramban */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dataset dibatasi untuk posisi lain */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Slug atau berkas tidak dikenal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    previewText: {
        parameters: {
            query?: {
                /** @description Berkas mana yang dibaca, dari daftar `resources`. */
                resourceId?: string;
            };
            header?: never;
            path: {
                /**
                 * @description Slug dataset.
                 * @example penjualan-bulanan
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Isi dokumen berhasil dibaca */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentTextResponse"];
                };
            };
            /** @description Berkas bukan DOCX atau gagal dibaca */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dataset dibatasi untuk posisi lain */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    download: {
        parameters: {
            query?: {
                /**
                 * @description Persetujuan pemakaian data. **Harus `true`**, dan ikut tercatat di audit log.
                 * @example true
                 */
                agreement?: boolean;
                /**
                 * @description Berkas mana yang diminta, diisi `id` dari daftar `resources` pada
                 *     `GET /api/v1/datasets/{slug}`. Boleh berprefiks (`dres-…`) maupun UUID polos.
                 *
                 *     Dikosongkan berarti berkas pertama. Satu permintaan mengambil satu berkas;
                 *     untuk beberapa berkas, panggil endpoint ini sekali per berkas supaya
                 *     masing-masing punya barisnya sendiri di log unduhan.
                 * @example dres-f0000000-0000-4000-8000-000000000001
                 */
                resourceId?: string;
            };
            header?: never;
            path: {
                /**
                 * @description Slug dataset. Hanya `penjualan-furnitur-2025` yang punya berkas.
                 * @example penjualan-furnitur-2025
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Berkas dialirkan. Nama berkasnya ada di header Content-Disposition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Persetujuan belum diberikan — agreement masih false */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
            /** @description Slug tidak dikenal, atau dataset itu memang tidak punya berkas */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    datastore: {
        parameters: {
            query?: {
                /**
                 * @description Halaman ke berapa, **dimulai dari 0**.
                 * @example 0
                 */
                page?: number;
                /**
                 * @description Jumlah baris per halaman. Minimal 1.
                 * @example 50
                 */
                size?: number;
                /**
                 * @description Tabel milik berkas yang mana, dari daftar `resources`. Kosongkan untuk berkas utama.
                 * @example dres-f0000000-0000-4000-8000-000000000001
                 */
                resourceId?: string;
            };
            header?: never;
            path: {
                /**
                 * @description Slug dataset. Hanya `penjualan-furnitur-2025` yang saat ini berisi data.
                 * @example penjualan-furnitur-2025
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Baris berhasil diambil. Bisa kosong kalau dataset belum berisi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DatastoreResponse"];
                };
            };
            /** @description Nilai page atau size tidak masuk akal, misalnya size 0 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
            /** @description Slug tidak dikenal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    index_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar koleksi berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectionResponse"][];
                };
            };
        };
    };
    getById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Slug koleksi. Ambil dari GET /api/v1/collections.
                 * @example komersial
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Koleksi ditemukan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectionResponse"];
                };
            };
            /** @description Slug tidak dikenal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    index_7: {
        parameters: {
            query?: {
                /**
                 * @description Halaman ke berapa, dimulai dari 0
                 * @example 0
                 */
                page?: number;
                /**
                 * @description Jumlah baris per halaman, maksimum 200
                 * @example 20
                 */
                size?: number;
                /**
                 * @description Saring ke satu dataset saja, diisi slug-nya
                 * @example penjualan-bulanan
                 */
                slug?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jejak audit berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAuditLogResponse"];
                };
            };
            /** @description Bukan ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
