/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cari dan saring daftar dataset
         * @description Mengembalikan daftar dataset berhalaman, sesuai isi halaman Datasets di portal.
         *
         *     **Cara tercepat menampilkan semua:** tekan Execute tanpa mengisi apa pun.
         *     Seluruh penyaring bersifat opsional — yang dikosongkan tidak dikirim.
         *
         *     **Contoh pemakaian:**
         *     - Cari kata kunci → isi `search` dengan `penjualan`
         *     - Saring dua topik → isi `topics` dua baris: `Keuangan` lalu `Operasional`
         *     - Saring dua divisi → isi `divisions` dua baris: `SALES` lalu `FIN`
         *     - Urutkan terpopuler → isi `sort` dengan `downloads`
         *
         *     **Membaca hasilnya:** `content` berisi datasetnya, `totalElements` jumlah seluruhnya,
         *     `totalPages` jumlah halaman, dan `number` halaman saat ini — **dimulai dari 0**, bukan 1.
         *
         *     Ambil nilai `slug` dari hasil di sini untuk dipakai di endpoint lain.
         */
        get: operations["index"];
        put?: never;
        /**
         * Terbitkan dataset baru dari berkas CSV
         * @description **Versi internal untuk pengujian.** Desain sisi penerbit belum ada, jadi bentuk
         *     layarnya masih bisa berubah — tapi pembagian tugasnya sudah pasti: apa yang bisa
         *     diverifikasi mesin dihitung sendiri, apa yang butuh pertanggungjawaban manusia diminta
         *     dari penerbit.
         *
         *     Permintaan berupa **multipart** dengan dua bagian:
         *     - `file` — berkas CSV, maksimal 10 MB
         *     - `body` — metadata dalam JSON
         *
         *     **Yang dihitung sendiri, tidak perlu diisi:**
         *
         *     | Field | Dari mana |
         *     |---|---|
         *     | `slug` | dibuat dari judul bila dikosongkan |
         *     | `division` | dari akun pengunggah — tidak bisa mengaku mewakili divisi lain |
         *     | `rowCount`, `colCount`, `fileSize` | dihitung dari berkasnya |
         *     | `format` | CSV |
         *     | daftar kolom, tipe data | dibaca dari header dan **isi** berkas |
         *
         *     **Soal tipe kolom:** untuk kolom di luar 17 kolom CSV penjualan furnitur, tipe data
         *     ditebak dari mencicipi 200 nilai pertama. Tebakannya konservatif — ragu berarti `Text`.
         *     Salah menebak kolom angka sebagai teks hanya membuat grafik tidak menawarkan kolom itu;
         *     sebaliknya akan membuat perhitungan diam-diam mengabaikan baris yang tidak terbaca dan
         *     menghasilkan angka yang salah tanpa peringatan.
         *
         *     **Soal slug:** kosongkan agar dibuatkan dari judul. Bila Anda mengisinya sendiri dan
         *     slug itu sudah dipakai, permintaan ditolak 400 beserta usulan yang tersedia — **tidak**
         *     diam-diam ditambahi angka, karena tautan yang sudah terlanjur dibagikan akan menunjuk
         *     ke tempat yang salah.
         *
         *     Perlu peran **ADMIN** atau **PUBLISHER**. Identitas uji yang bisa dipakai:
         *     `dummy-admin`, `dummy-director`, `dummy-corpsec`, `dummy-manager`.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar API key milik saya
         * @description Seluruh key milik pengguna yang sedang login, beserta nama, waktu pembuatan, dan
         *     waktu pemakaian terakhir.
         *
         *     **Nilai key-nya tidak ikut di sini** — yang tampil hanya bentuk tersamar
         *     (`masked`). Untuk nilai penuh, panggil `GET /api/v1/api-keys/{id}/reveal` satu kunci
         *     pada satu waktu, supaya nilai kunci tidak berhamburan di respons daftar.
         */
        get: operations["index_1"];
        put?: never;
        /**
         * Buat API key baru
         * @description Membuat kunci akses baru untuk pengguna yang sedang login.
         *
         *     **Cara mengisi:** badan permintaan hanya butuh satu field, `name` — label bebas supaya
         *     Anda ingat key itu dipakai untuk apa. Contoh:
         *
         *     ```json
         *     { "name": "Integrasi dashboard tim Sales" }
         *     ```
         *
         *     `plainKey` di respons adalah nilai kuncinya. Nilai itu juga bisa dilihat lagi kapan
         *     saja lewat `GET /api/v1/api-keys/{id}/reveal`, karena kunci disimpan terenkripsi.
         *
         *     Ada batas jumlah key aktif per pengguna; kalau tercapai, permintaan ditolak 400 dan
         *     key lama harus dicabut lebih dulu.
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar seluruh topik
         * @description Delapan topik yang dipakai mengelompokkan dataset, sesuai chip penyaring di halaman
         *     Datasets portal.
         *
         *     Nilai `name` dari sini yang diisikan ke parameter `topics` pada
         *     `GET /api/v1/datasets`. Contoh: `Keuangan`, `Operasional`.
         *
         *     Tidak perlu login.
         */
        get: operations["indexTopic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kesehatan tiap komponen portal
         * @description Memeriksa setiap komponen secara nyata saat dipanggil — database benar-benar
         *     di-ping, penyimpanan berkas benar-benar dicek.
         *
         *     Tanpa parameter apa pun; langsung Execute.
         *
         *     **Catatan jujur:** komponen "Real-time API" akan selalu melaporkan *Belum tersedia*,
         *     bukan *Operasional* — karena fitur itu memang belum dibangun. Itu disengaja; melaporkan
         *     hijau untuk sesuatu yang tidak ada hanya menyesatkan orang yang membaca halaman status.
         *
         *     Endpoint ini berbeda dari `/actuator/health` bawaan Spring: yang ini memakai bahasa dan
         *     pengelompokan sesuai desain halaman Status, sedangkan actuator untuk pemantauan mesin.
         */
        get: operations["index_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Angka ringkas seluruh portal
         * @description Jumlah dataset, divisi penerbit, total kunjungan, total unduhan, dan total panggilan
         *     API — dihitung langsung dari database saat dipanggil, bukan nilai tetap.
         *
         *     Tanpa parameter apa pun; langsung Execute.
         *
         *     Nama endpoint ini sudah jamak sejak awal karena `stats` memang bentuk jamak dari
         *     *statistic*, bukan pengecualian dari konvensi.
         */
        get: operations["index_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profil pengguna yang sedang login
         * @description Identitas pemanggil: nama, email, jabatan, divisi, peran portal, dan tingkat izin
         *     hasil hitungan HRIS.
         *
         *     Dipakai portal untuk mengisi pil identitas di header setiap halaman.
         *
         *     **Cara mencoba di Swagger:** tekan Authorize, isi `dummyAuth` dengan salah satu
         *     identitas uji, lalu Execute di sini. Nama yang muncul harus sesuai identitas yang
         *     Anda pilih.
         *
         *     | Isi `dummyAuth` | Hasil |
         *     |---|---|
         *     | `dummy-admin` | 200, peran ADMIN |
         *     | `dummy-director` | 200, izin HRIS DIRECTOR |
         *     | `dummy-staff` | 200, peran STAFF |
         *     | `dummy-resigned` | **403** — sengaja, user itu sudah resign |
         *     | *(tanpa Authorize)* | **401** |
         *
         *     Perhatikan `role` (peran di portal) berbeda dari `hrisPermissionLevel` (tingkat izin
         *     dari sistem HRIS). Keduanya sengaja dipisah karena sumbernya berbeda.
         *
         *     ⚠️ Peran portal saat ini **belum menegakkan apa pun** — belum ada satu pun
         *     `@PreAuthorize` di kode. Semua pengguna terautentikasi bisa memanggil semua endpoint.
         *     Itu masih aman karena seluruh endpoint bersifat baca atau sudah dibatasi per-pengguna,
         *     tapi penegakan role wajib ada sebelum sisi admin dibangun.
         */
        get: operations["index_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/formats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar seluruh format berkas
         * @description Format berkas yang tersedia di katalog: CSV, XLSX, GEOJSON, KML, dan API.
         *
         *     Nilai `name` dari sini yang diisikan ke parameter `formats` pada
         *     `GET /api/v1/datasets`.
         *
         *     Catatan: `API` bukan berkas — itu penanda dataset yang dialirkan langsung tanpa
         *     unduhan. Dan **PDF belum ada di daftar ini**, padahal ada dokumen PDF di berkas
         *     proyek; itu celah yang masih perlu diputuskan tim.
         *
         *     Tidak perlu login.
         */
        get: operations["indexFormat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/divisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar seluruh divisi
         * @description Delapan divisi beserta kode, nama, warna avatar, dan penghitung pemakaian
         *     (`apiCalls`, `downloads`).
         *
         *     **Nilai `code` dari sini yang diisikan ke parameter `divisions`** pada
         *     `GET /api/v1/datasets` untuk menyaring dataset per divisi penerbit:
         *     `DNA`, `IT`, `PROD`, `SALES`, `FIN`, `OPS`, `HR`, `MKT`.
         *
         *     Mengisi parameter itu dengan nama panjang seperti `Divisi Penjualan` tidak akan
         *     menyaring apa pun — yang dipakai kodenya.
         */
        get: operations["index_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ambil metadata lengkap satu dataset
         * @description Semua keterangan tentang satu dataset: judul, divisi penerbit, catatan, disclaimer,
         *     koleksi induk, daftar topik dan format, jumlah baris dan kolom, serta **skema kolomnya**
         *     (nama mesin, nama tampilan, tipe data, satuan).
         *
         *     Dipakai halaman detail dataset di portal untuk mengisi tab Ringkasan dan tab Kolom.
         *
         *     Perhatikan `resources` — kalau kosong, dataset itu tidak punya berkas untuk diunduh.
         */
        get: operations["getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{slug}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hitung agregat untuk bahan grafik
         * @description Mengelompokkan isi dataset lalu menghitung jumlahnya — inilah yang menggambar grafik
         *     di halaman detail portal.
         *
         *     **Cara mengisi:**
         *     - `groupBy` **wajib** — nama kolom yang jadi pengelompokan, nantinya sumbu X grafik
         *     - `metric` opsional — nama kolom angka yang dijumlahkan. Kalau dikosongkan, yang keluar
         *       hanya `count` (banyaknya baris per kelompok)
         *
         *     **Contoh untuk `penjualan-furnitur-2025`:**
         *     | Ingin melihat | `groupBy` | `metric` |
         *     |---|---|---|
         *     | Penjualan per kategori produk | `category` | `total_sales` |
         *     | Penjualan per kota | `kota` | `total_sales` |
         *     | Banyaknya transaksi per status | `status` | *(kosongkan)* |
         *     | Jumlah barang terjual per kategori | `category` | `quantity` |
         *
         *     Nama kolom yang boleh dipakai bisa dilihat dari `columns` pada
         *     `GET /api/v1/datasets/{slug}`.
         *
         *     **Peringatan angka:** kolom `status` memuat `completed`, `cancelled`, dan `refund`.
         *     Menjumlahkan `total_sales` tanpa menyaring status berarti transaksi batal ikut terhitung
         *     — jadi angkanya bukan pendapatan bersih. Penyaringan per status belum tersedia di
         *     endpoint ini.
         */
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{slug}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unduh berkas asli dataset
         * @description Mengalirkan berkas sumber dataset apa adanya, tanpa perubahan sebyte pun.
         *
         *     **`agreement` wajib diisi `true`.** Itu bukan formalitas: nilainya mewakili centang
         *     persetujuan pemakaian data pada modal di portal, dan **ikut tercatat di audit log**
         *     bersama identitas pengunduh, waktu, alamat IP, dan User-Agent. Dikirim `false` →
         *     ditolak 400. Jangan pernah mengirim `true` secara otomatis tanpa pengguna benar-benar
         *     menyetujuinya.
         *
         *     **Catatan saat mencoba lewat Swagger:** responsnya berkas 1,4 MB, dan Swagger UI akan
         *     mencoba menampilkannya sebagai teks sebelum memberi tombol "Download file" — browser
         *     bisa terasa berat beberapa detik. Untuk sekadar menguji, lebih nyaman memakai `curl`.
         *     Yang justru berguna dicoba di sini adalah kasus gagalnya: biarkan `agreement` bernilai
         *     `false` lalu Execute, harus dijawab 400.
         */
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{slug}/datastore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Baca isi tabel dataset per halaman
         * @description Isi baris data yang sesungguhnya — yang tampil di tab **Data Explorer** portal.
         *
         *     `columns` memberi urutan kolomnya, `rows` berisi datanya sebagai objek bebas
         *     (satu objek per baris, kuncinya nama kolom).
         *
         *     **Contoh:** slug `penjualan-furnitur-2025`, `page` 0, `size` 50 → 50 baris pertama
         *     dari 10.000 baris penjualan furnitur.
         *
         *     Naikkan `page` untuk melihat baris berikutnya. Dengan `size` 50, halaman 0 berisi baris
         *     1–50, halaman 1 berisi 51–100, dan seterusnya.
         */
        get: operations["datastore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar seluruh koleksi
         * @description Semua koleksi beserta nama, keterangan, dan divisi pengelolanya.
         *
         *     Ambil nilai `slug` dari sini untuk membuka detailnya.
         */
        get: operations["index_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ambil satu koleksi beserta dataset di dalamnya
         * @description Keterangan lengkap satu koleksi berikut daftar dataset anggotanya.
         *
         *     Seperti pada dataset, path parameternya **slug**, bukan UUID. Ambil nilainya dari
         *     `GET /api/v1/collections`.
         */
        get: operations["getById_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{id}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tampilkan nilai API key seutuhnya
         * @description Melayani tombol **Tampilkan** di Dasbor Akun — mengembalikan nilai kunci hasil
         *     dekripsi.
         *
         *     Hanya kunci milik sendiri yang bisa diungkap. Kunci milik orang lain dijawab 404
         *     seolah tidak ada, bukan 403 — supaya keberadaannya pun tidak bocor.
         *
         *     Kunci yang sudah **dicabut** tetap boleh diungkap. Itu disengaja: pemiliknya berhak
         *     tahu nilai apa yang harus dicari dan dibersihkan dari skrip yang mungkin masih
         *     memakainya.
         *
         *     **Tiga kunci yang dibuat sebelum fitur ini ada tidak punya ciphertext** dan akan
         *     dijawab 400 dengan penjelasan — bukan galat yang membingungkan.
         */
        get: operations["reveal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cabut API key
         * @description Menonaktifkan satu key milik sendiri secara permanen. Tidak bisa dibatalkan.
         *
         *     **Perhatikan:** di sini path parameternya **UUID**, berbeda dengan endpoint dataset yang
         *     memakai slug. Alasannya API key tidak punya nama publik dan tidak pernah muncul di URL
         *     yang dibagikan — jadi identitas internalnya yang dipakai.
         *
         *     Ambil nilai `id` dari `GET /api/v1/api-keys`.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DatasetRequestCreateDTO: {
            /**
             * @description Nama dataset seperti yang akan dibaca orang. Ini klaim tentang apa data ini — tidak bisa ditebak dari berkasnya, jadi wajib ditulis penerbit.
             * @example Penjualan Furnitur Ritel 2025
             */
            title: string;
            /**
             * @description Alamat dataset di URL. **Kosongkan** dan sistem membuatnya dari judul. Isi hanya bila ingin lebih pendek, misalnya `utilisasi-sdm` untuk judul "Utilisasi & Kapasitas Tim". Huruf kecil, angka, dan tanda hubung saja. Setelah terbit, slug tidak bisa diubah karena sudah jadi tautan di laporan orang.
             * @example penjualan-furnitur-2025
             */
            slug?: string;
            /**
             * @description Penjelasan isi dataset dan cara membacanya.
             * @example Transaksi penjualan furnitur ritel sepanjang 2025 per pesanan.
             */
            notes?: string;
            /**
             * @description Hal yang harus diketahui pembaca agar datanya tidak salah ditafsirkan: angka yang masih sementara, batas cakupan, atau dasar perhitungan. Ditampilkan sebagai blok terpisah di halaman detail.
             * @example Status refund dan cancelled dihitung apa adanya tanpa rekonsiliasi keuangan.
             */
            disclaimer?: string;
            /**
             * @description Periode yang dicakup data.
             * @example Jan – Des 2025
             */
            coverage?: string;
            /**
             * @description Nama topik, ambil dari GET /api/v1/topics. Boleh lebih dari satu.
             * @example [
             *       "Penjualan"
             *     ]
             */
            topics?: string[];
            /**
             * @description Slug koleksi induk, ambil dari GET /api/v1/collections. Boleh kosong.
             * @example komersial
             */
            collectionSlug?: string;
        };
        CollectionResponseLite: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            name?: string;
        };
        DatasetColumnResponse: {
            /** Format: uuid */
            id?: string;
            machineName?: string;
            displayName?: string;
            dataType?: string;
            unit?: string;
            description?: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        DatasetResourceResponse: {
            /** Format: uuid */
            id?: string;
            fileName?: string;
            formatName?: string;
            contentType?: string;
            /** Format: int64 */
            sizeBytes?: number;
            checksumSha256?: string;
        };
        DatasetResponse: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            title?: string;
            division?: components["schemas"]["DivisionResponseLite"];
            collection?: components["schemas"]["CollectionResponseLite"];
            topics?: string[];
            formats?: string[];
            coverage?: string;
            notes?: string;
            disclaimer?: string;
            /** Format: int64 */
            rowCount?: number;
            /** Format: int32 */
            colCount?: number;
            fileSize?: string;
            /** Format: int64 */
            downloads?: number;
            /** Format: int64 */
            apiCalls?: number;
            /** Format: int64 */
            views?: number;
            realtime?: boolean;
            /** Format: date-time */
            lastUpdatedAt?: string;
            columns?: components["schemas"]["DatasetColumnResponse"][];
            resources?: components["schemas"]["DatasetResourceResponse"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string;
        };
        DivisionResponseLite: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            logoBg?: string;
        };
        ApiKeyRequestCreateDTO: {
            name: string;
        };
        ApiKeyCreatedResponse: {
            key?: components["schemas"]["ApiKeyResponse"];
            plainKey?: string;
            warning?: string;
        };
        ApiKeyResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            keyPrefix?: string;
            masked?: string;
            tier?: string;
            /** Format: int32 */
            rateLimitPerMinute?: number;
            /** Format: int64 */
            usageCount?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "REVOKED";
            /** Format: date-time */
            lastUsedAt?: string;
            /** Format: date-time */
            revokedAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        TopicResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        Component: {
            name?: string;
            state?: string;
        };
        IncidentItem: {
            /** Format: uuid */
            id?: string;
            title?: string;
            tag?: string;
            detail?: string;
            occurredLabel?: string;
            /** Format: date-time */
            occurredAt?: string;
        };
        StatusResponse: {
            overall?: string;
            overallLabel?: string;
            components?: components["schemas"]["Component"][];
            incidents?: components["schemas"]["IncidentItem"][];
        };
        StatsResponse: {
            /** Format: int64 */
            totalDataset?: number;
            /** Format: int64 */
            totalFormat?: number;
            /** Format: int64 */
            totalDivision?: number;
            /** Format: int64 */
            totalTopic?: number;
            /** Format: int64 */
            totalCollection?: number;
            /** Format: int64 */
            totalDownloads?: number;
            /** Format: int64 */
            totalApiCalls?: number;
            /** Format: int64 */
            totalViews?: number;
            /** Format: int64 */
            totalDatasetWithFile?: number;
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            email?: string;
            position?: string;
            initials?: string;
            /** @enum {string} */
            role?: "ADMIN" | "PUBLISHER" | "STAFF";
            /** @enum {string} */
            hrisPermissionLevel?: "ADMIN" | "DIRECTOR" | "CORPORATE_SECRETARY" | "MANAGER" | "STAFF";
            jobLevel?: string;
            division?: components["schemas"]["DivisionResponseLite"];
        };
        FormatResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        DivisionResponse: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            logoBg?: string;
            /** Format: int64 */
            apiCalls?: number;
            /** Format: int64 */
            downloads?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string;
        };
        DatasetResponseLite: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            title?: string;
            division?: components["schemas"]["DivisionResponseLite"];
            topics?: string[];
            formats?: string[];
            coverage?: string;
            notes?: string;
            /** Format: int64 */
            downloads?: number;
            /** Format: int64 */
            apiCalls?: number;
            /** Format: int64 */
            views?: number;
            realtime?: boolean;
            /** Format: date-time */
            lastUpdatedAt?: string;
        };
        PageDatasetResponseLite: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["DatasetResponseLite"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        DatasetSummaryResponse: {
            slug?: string;
            groupBy?: string;
            metric?: string;
            /** Format: int64 */
            totalRows?: number;
            groups?: components["schemas"]["SummaryGroup"][];
        };
        SummaryGroup: {
            label?: string;
            /** Format: int64 */
            count?: number;
            sum?: number;
        };
        DatastoreResponse: {
            slug?: string;
            /** Format: int64 */
            totalRows?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int32 */
            totalPages?: number;
            columns?: components["schemas"]["DatasetColumnResponse"][];
            rows?: {
                [key: string]: unknown;
            }[];
        };
        CollectionResponse: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            name?: string;
            description?: string;
            division?: components["schemas"]["DivisionResponseLite"];
            /** Format: int64 */
            datasetCount?: number;
            datasets?: components["schemas"]["DatasetResponseLite"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string;
        };
        ApiKeyRevealResponse: {
            /**
             * @description Nilai API key seutuhnya, hasil dekripsi.
             * @example erd_live_9f2a8c31d4e7b0a25f6c9081b3e7a4d2
             */
            plainKey?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    index: {
        parameters: {
            query?: {
                /**
                 * @description Kata kunci pada judul dan catatan dataset. Kosongkan untuk menampilkan semua.
                 * @example penjualan
                 */
                search?: string;
                /** @description Saring per topik. Ulangi parameter untuk lebih dari satu, misalnya topics=Keuangan&topics=Operasional. Daftar nilainya dari GET /api/v1/topic. */
                topics?: string[];
                /** @description Saring per format berkas. Daftar nilainya dari GET /api/v1/format. */
                formats?: string[];
                /** @description Saring per kode divisi: DNA, IT, PROD, SALES, FIN, OPS, HR, MKT. Daftar lengkapnya dari GET /api/v1/division. */
                divisions?: string[];
                /** @description Urutan hasil. */
                sort?: "relevance" | "downloads" | "updated";
                /** @description Halaman ke berapa, dimulai dari 0. */
                page?: number;
                /** @description Jumlah baris per halaman. Minimal 1. */
                size?: number;
                /** @description Ikut menampilkan dataset yang sudah dihapus. */
                withDeleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar dataset berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageDatasetResponseLite"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Berkas CSV, maksimal 10 MB.
                     */
                    file: string;
                    body: components["schemas"]["DatasetRequestCreateDTO"];
                };
            };
        };
        responses: {
            /** @description Dataset terbit, berikut isi tabel dan berkasnya */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Berkas bukan CSV, judul kosong, slug bentrok, atau topik/koleksi tidak dikenal */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
            /** @description Peran Anda tidak berhak menerbitkan dataset */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    index_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar key berhasil diambil. Bisa berupa daftar kosong */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiKeyResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyRequestCreateDTO"];
            };
        };
        responses: {
            /** @description Key dibuat. Nilai plainKey hanya muncul di respons ini */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiKeyCreatedResponse"];
                };
            };
            /** @description Batas key aktif tercapai, atau nama tidak diisi */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    indexTopic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar topik berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopicResponse"][];
                };
            };
        };
    };
    index_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status berhasil diperiksa. Kode 200 tidak berarti semua komponen sehat — periksa isi responsnya */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    index_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistik berhasil dihitung */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    index_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil berhasil diambil — berarti autentikasi Anda benar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
            /** @description Belum Authorize, atau identitas tidak dikenal */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        message?: string;
                    };
                };
            };
            /** @description Karyawan sudah resign sehingga aksesnya ditolak */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    indexFormat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar format berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FormatResponse"][];
                };
            };
        };
    };
    index_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar divisi berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DivisionResponse"][];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identitas dataset di URL — berupa **slug**, bukan UUID.
                 *
                 *     Slug adalah versi judul yang aman dipakai di URL: huruf kecil, spasi diganti
                 *     tanda hubung. Contoh: judul "Penjualan Furnitur Ritel 2025" berslug
                 *     `penjualan-furnitur-2025`.
                 *
                 *     Daftar slug yang tersedia bisa dilihat dari `GET /api/v1/datasets`.
                 * @example penjualan-furnitur-2025
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dataset ditemukan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Slug tidak dikenal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    summary: {
        parameters: {
            query: {
                /**
                 * @description Nama kolom pengelompokan — jadi sumbu X grafik. Contoh lain: `kota`, `status`.
                 * @example category
                 */
                groupBy: string;
                /**
                 * @description Nama kolom angka yang dijumlahkan. Kosongkan untuk sekadar menghitung banyaknya baris.
                 * @example total_sales
                 */
                metric?: string;
            };
            header?: never;
            path: {
                /**
                 * @description Slug dataset.
                 * @example penjualan-furnitur-2025
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agregat berhasil dihitung */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DatasetSummaryResponse"];
                };
            };
            /** @description Kolom groupBy atau metric tidak ada di dataset ini */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
            /** @description Slug tidak dikenal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    download: {
        parameters: {
            query?: {
                /**
                 * @description Persetujuan pemakaian data. **Harus `true`**, dan ikut tercatat di audit log.
                 * @example true
                 */
                agreement?: boolean;
            };
            header?: never;
            path: {
                /**
                 * @description Slug dataset. Hanya `penjualan-furnitur-2025` yang punya berkas.
                 * @example penjualan-furnitur-2025
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Berkas dialirkan. Nama berkasnya ada di header Content-Disposition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Persetujuan belum diberikan — agreement masih false */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
            /** @description Slug tidak dikenal, atau dataset itu memang tidak punya berkas */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    datastore: {
        parameters: {
            query?: {
                /**
                 * @description Halaman ke berapa, **dimulai dari 0**.
                 * @example 0
                 */
                page?: number;
                /**
                 * @description Jumlah baris per halaman. Minimal 1.
                 * @example 50
                 */
                size?: number;
            };
            header?: never;
            path: {
                /**
                 * @description Slug dataset. Hanya `penjualan-furnitur-2025` yang saat ini berisi data.
                 * @example penjualan-furnitur-2025
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Baris berhasil diambil. Bisa kosong kalau dataset belum berisi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DatastoreResponse"];
                };
            };
            /** @description Nilai page atau size tidak masuk akal, misalnya size 0 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
            /** @description Slug tidak dikenal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    index_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar koleksi berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectionResponse"][];
                };
            };
        };
    };
    getById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Slug koleksi. Ambil dari GET /api/v1/collections.
                 * @example komersial
                 */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Koleksi ditemukan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectionResponse"];
                };
            };
            /** @description Slug tidak dikenal */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    reveal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Id kunci dalam bentuk `key-<uuid>` seperti yang muncul di GET /api/v1/api-keys. UUID telanjang tanpa awalan juga diterima.
                 * @example key-3fa85f64-5717-4562-b3fc-2c963f66afa6
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nilai kunci berhasil didekripsi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiKeyRevealResponse"];
                };
            };
            /** @description Kunci dibuat sebelum penyimpanan terenkripsi ada, jadi nilainya tidak tersimpan */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
            /** @description Kunci tidak ditemukan, atau bukan milik Anda */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Id kunci dalam bentuk `key-<uuid>` seperti yang muncul di GET /api/v1/api-keys. UUID telanjang tanpa awalan juga diterima.
                 * @example key-3fa85f64-5717-4562-b3fc-2c963f66afa6
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key berhasil dicabut */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Key tidak ditemukan, atau bukan milik Anda */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        error?: string;
                    };
                };
            };
        };
    };
}
